### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by SebastianZimmeck**

### CODE REVIEW

**Comment by SebastianZimmeck** [comment]
@dmarti, can you review this change? I would like to add a .gitignore.

**Review by quantumpacket — APPROVED** [review]

**Review by dmarti — APPROVED** [review]
Looks good to me

**Review by dmarti — APPROVED** [review]

**Review by dmarti — APPROVED** [review]
Re-approving, sorry for any notification noise

**Review by pes10k — APPROVED** [review]
lgtm

**Pull request merged**
